CXX=g++
CFLAGS=-std=c++17 -Wall -pedantic -lSDL2 -lSDL2_image -O3
OBJS=./obj/main.o ./obj/tank.o ./obj/tile_crate.o ./obj/dummy_io_device.o ./obj/sdl_io_device.o ./obj/io_device.o ./obj/world.o ./obj/texture_pack.o ./obj/game_object.o ./obj/entity.o ./obj/tile_bricks.o ./obj/i_physical.o ./obj/tile_air.o ./obj/tile_steel.o ./obj/tile.o ./obj/point_2d.o ./obj/i_directional.o ./obj/tank_game.o ./obj/projectile.o ./obj/explosion.o ./obj/i_damageable.o ./obj/game_context.o ./obj/ai_tank.o ./obj/entity_ammo.o ./obj/entity_bonus.o ./obj/entity_max_health.o ./obj/entity_speed.o ./obj/entity_repair.o

all: compile doc

compile: hlavaadr

hlavaadr: $(OBJS)
	$(CXX) $(CFLAGS) -o $@ $^ -lstdc++fs

run: compile
	./hlavaadr $(ARGS)

doc: ./src/*.hpp ./src/GameObjects/*.hpp ./src/*.cpp ./src/GameObjects/*.cpp
	doxygen doxyConfig

clean: 
	rm -rf ./obj ./doc hlavaadr

./obj/%.o: ./src/%.cpp
	mkdir -p obj
	$(CXX) $(CFLAGS) -c $< -o$@

./obj/%.o: ./src/GameObjects/%.cpp
	mkdir -p obj
	$(CXX) $(CFLAGS) -c $< -o$@

#GENERATED BY g++ -MM , then fixed

dummy_io_device.o: src/dummy_io_device.cpp src/dummy_io_device.hpp \
 src/io_device.hpp src/world.hpp src/tile.hpp src/game_object.hpp \
 src/game_context.hpp src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp src/e_textures.hpp \
 src/entity.hpp src/GameObjects/tank.hpp src/entity.hpp \
 src/i_directional.hpp src/point_2d.hpp \
 src/e_direction.hpp src/game_context.hpp \
 src/i_damageable.hpp src/tank_game.hpp
dummy_io_device.o: src/dummy_io_device.hpp src/io_device.hpp \
 src/world.hpp src/tile.hpp src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp src/e_direction.hpp \
 src/texture_pack.hpp src/e_textures.hpp src/entity.hpp \
 src/GameObjects/tank.hpp src/entity.hpp \
 src/i_directional.hpp src/point_2d.hpp \
 src/e_direction.hpp src/game_context.hpp \
 src/i_damageable.hpp
e_direction.o: src/e_direction.hpp
entity_bonus.o: src/entity_bonus.cpp src/entity_bonus.hpp src/entity.hpp \
 src/game_object.hpp src/game_context.hpp src/i_physical.hpp \
 src/point_2d.hpp src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp src/world.hpp src/tile.hpp src/GameObjects/tank.hpp \
 src/entity.hpp src/i_directional.hpp \
 src/point_2d.hpp src/e_direction.hpp \
 src/game_context.hpp src/i_damageable.hpp \
 src/GameObjects/entity_ammo.hpp src/entity_bonus.hpp \
 src/GameObjects/entity_max_health.hpp src/GameObjects/entity_speed.hpp \
 src/GameObjects/entity_repair.hpp
entity_bonus.o: src/entity_bonus.hpp src/entity.hpp src/game_object.hpp \
 src/game_context.hpp src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp src/e_textures.hpp
entity.o: src/entity.cpp src/entity.hpp src/game_object.hpp \
 src/game_context.hpp src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp src/e_textures.hpp
entity.o: src/entity.hpp src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp src/e_direction.hpp \
 src/texture_pack.hpp src/e_textures.hpp
e_textures.o: src/e_textures.hpp
game_context.o: src/game_context.cpp src/game_context.hpp \
 src/tank_game.hpp src/io_device.hpp src/world.hpp src/tile.hpp \
 src/game_object.hpp src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp src/e_textures.hpp \
 src/entity.hpp src/GameObjects/tank.hpp src/entity.hpp \
 src/i_directional.hpp src/point_2d.hpp \
 src/e_direction.hpp src/game_context.hpp \
 src/i_damageable.hpp
game_context.o: src/game_context.hpp
game_object.o: src/game_object.cpp src/game_object.hpp \
 src/game_context.hpp
game_object.o: src/game_object.hpp src/game_context.hpp
i_damageable.o: src/i_damageable.cpp src/i_damageable.hpp \
 src/game_context.hpp
i_damageable.o: src/i_damageable.hpp src/game_context.hpp
i_directional.o: src/i_directional.cpp src/i_directional.hpp \
 src/point_2d.hpp src/e_direction.hpp src/game_context.hpp
i_directional.o: src/i_directional.hpp src/point_2d.hpp \
 src/e_direction.hpp src/game_context.hpp
io_device.o: src/io_device.cpp src/io_device.hpp src/world.hpp \
 src/tile.hpp src/game_object.hpp src/game_context.hpp src/i_physical.hpp \
 src/point_2d.hpp src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp src/entity.hpp src/GameObjects/tank.hpp \
 src/entity.hpp src/i_directional.hpp \
 src/point_2d.hpp src/e_direction.hpp \
 src/game_context.hpp src/i_damageable.hpp
io_device.o: src/io_device.hpp src/world.hpp src/tile.hpp \
 src/game_object.hpp src/game_context.hpp src/i_physical.hpp \
 src/point_2d.hpp src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp src/entity.hpp src/GameObjects/tank.hpp \
 src/entity.hpp src/i_directional.hpp \
 src/point_2d.hpp src/e_direction.hpp \
 src/game_context.hpp src/i_damageable.hpp
i_physical.o: src/i_physical.cpp src/i_physical.hpp src/game_object.hpp \
 src/game_context.hpp src/point_2d.hpp src/e_direction.hpp \
 src/texture_pack.hpp src/e_textures.hpp src/world.hpp src/tile.hpp \
 src/entity.hpp src/GameObjects/tank.hpp src/entity.hpp \
 src/i_directional.hpp src/point_2d.hpp \
 src/e_direction.hpp src/game_context.hpp \
 src/i_damageable.hpp
i_physical.o: src/i_physical.hpp src/game_object.hpp src/game_context.hpp \
 src/point_2d.hpp src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp
main.o: src/main.cpp src/tank_game.hpp src/io_device.hpp src/world.hpp \
 src/tile.hpp src/game_object.hpp src/game_context.hpp src/i_physical.hpp \
 src/point_2d.hpp src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp src/entity.hpp src/GameObjects/tank.hpp \
 src/entity.hpp src/i_directional.hpp \
 src/point_2d.hpp src/e_direction.hpp \
 src/game_context.hpp src/i_damageable.hpp \
 src/sdl_io_device.hpp src/dummy_io_device.hpp
point_2d.o: src/point_2d.cpp src/point_2d.hpp src/e_direction.hpp
point_2d.o: src/point_2d.hpp src/e_direction.hpp
sdl_io_device.o: src/sdl_io_device.cpp src/sdl_io_device.hpp \
 src/io_device.hpp src/world.hpp src/tile.hpp src/game_object.hpp \
 src/game_context.hpp src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp src/e_textures.hpp \
 src/entity.hpp src/GameObjects/tank.hpp src/entity.hpp \
 src/i_directional.hpp src/point_2d.hpp \
 src/e_direction.hpp src/game_context.hpp \
 src/i_damageable.hpp
sdl_io_device.o: src/sdl_io_device.hpp src/io_device.hpp src/world.hpp \
 src/tile.hpp src/game_object.hpp src/game_context.hpp src/i_physical.hpp \
 src/point_2d.hpp src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp src/entity.hpp src/GameObjects/tank.hpp \
 src/entity.hpp src/i_directional.hpp \
 src/point_2d.hpp src/e_direction.hpp \
 src/game_context.hpp src/i_damageable.hpp
tank_game.o: src/tank_game.cpp src/tank_game.hpp src/io_device.hpp \
 src/world.hpp src/tile.hpp src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp src/e_direction.hpp \
 src/texture_pack.hpp src/e_textures.hpp src/entity.hpp \
 src/GameObjects/tank.hpp src/entity.hpp \
 src/i_directional.hpp src/point_2d.hpp \
 src/e_direction.hpp src/game_context.hpp \
 src/i_damageable.hpp
tank_game.o: src/tank_game.hpp src/io_device.hpp src/world.hpp \
 src/tile.hpp src/game_object.hpp src/game_context.hpp src/i_physical.hpp \
 src/point_2d.hpp src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp src/entity.hpp src/GameObjects/tank.hpp \
 src/entity.hpp src/i_directional.hpp \
 src/point_2d.hpp src/e_direction.hpp \
 src/game_context.hpp src/i_damageable.hpp
texture_pack.o: src/texture_pack.cpp src/texture_pack.hpp \
 src/e_textures.hpp
texture_pack.o: src/texture_pack.hpp src/e_textures.hpp
tile.o: src/tile.cpp src/tile.hpp src/game_object.hpp \
 src/game_context.hpp src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp src/e_textures.hpp
tile.o: src/tile.hpp src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp src/e_direction.hpp \
 src/texture_pack.hpp src/e_textures.hpp
world.o: src/world.cpp src/world.hpp src/tile.hpp src/game_object.hpp \
 src/game_context.hpp src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp src/e_textures.hpp \
 src/entity.hpp src/GameObjects/tank.hpp src/entity.hpp \
 src/i_directional.hpp src/point_2d.hpp \
 src/e_direction.hpp src/game_context.hpp \
 src/i_damageable.hpp src/GameObjects/tile_air.hpp \
 src/tile.hpp src/GameObjects/tile_steel.hpp \
 src/GameObjects/tile_bricks.hpp src/GameObjects/tile_crate.hpp \
 src/GameObjects/ai_tank.hpp src/GameObjects/tank.hpp src/tank_game.hpp \
 src/io_device.hpp
world.o: src/world.hpp src/tile.hpp src/game_object.hpp \
 src/game_context.hpp src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp src/e_textures.hpp \
 src/entity.hpp src/GameObjects/tank.hpp src/entity.hpp \
 src/i_directional.hpp src/point_2d.hpp \
 src/e_direction.hpp src/game_context.hpp \
 src/i_damageable.hpp
ai_tank.o: src/GameObjects/ai_tank.cpp src/GameObjects/ai_tank.hpp \
 src/GameObjects/tank.hpp src/entity.hpp \
 src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp src/i_directional.hpp \
 src/i_damageable.hpp src/tank_game.hpp \
 src/io_device.hpp src/world.hpp \
 src/tile.hpp src/entity.hpp \
 src/GameObjects/tank.hpp \
 src/entity_bonus.hpp src/GameObjects/projectile.hpp \
 src/GameObjects/tile_crate.hpp src/tile.hpp \
 src/GameObjects/tile_bricks.hpp
ai_tank.o: src/GameObjects/ai_tank.hpp src/GameObjects/tank.hpp \
 src/entity.hpp src/game_object.hpp \
 src/game_context.hpp src/i_physical.hpp \
 src/point_2d.hpp src/e_direction.hpp \
 src/texture_pack.hpp src/e_textures.hpp \
 src/i_directional.hpp src/i_damageable.hpp
entity_ammo.o: src/GameObjects/entity_ammo.cpp \
 src/GameObjects/entity_ammo.hpp src/entity_bonus.hpp \
 src/entity.hpp src/game_object.hpp \
 src/game_context.hpp src/i_physical.hpp \
 src/point_2d.hpp src/e_direction.hpp \
 src/texture_pack.hpp src/e_textures.hpp \
 src/world.hpp src/tile.hpp \
 src/GameObjects/tank.hpp \
 src/entity.hpp \
 src/i_directional.hpp \
 src/point_2d.hpp \
 src/e_direction.hpp \
 src/game_context.hpp \
 src/i_damageable.hpp
entity_ammo.o: src/GameObjects/entity_ammo.hpp \
 src/entity_bonus.hpp src/entity.hpp \
 src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp
entity_max_health.o: src/GameObjects/entity_max_health.cpp \
 src/GameObjects/entity_max_health.hpp \
 src/entity_bonus.hpp src/entity.hpp \
 src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp src/world.hpp \
 src/tile.hpp src/GameObjects/tank.hpp \
 src/entity.hpp \
 src/i_directional.hpp \
 src/point_2d.hpp \
 src/e_direction.hpp \
 src/game_context.hpp \
 src/i_damageable.hpp
entity_max_health.o: src/GameObjects/entity_max_health.hpp \
 src/entity_bonus.hpp src/entity.hpp \
 src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp
entity_repair.o: src/GameObjects/entity_repair.cpp \
 src/GameObjects/entity_repair.hpp src/entity_bonus.hpp \
 src/entity.hpp src/game_object.hpp \
 src/game_context.hpp src/i_physical.hpp \
 src/point_2d.hpp src/e_direction.hpp \
 src/texture_pack.hpp src/e_textures.hpp \
 src/world.hpp src/tile.hpp \
 src/GameObjects/tank.hpp \
 src/entity.hpp \
 src/i_directional.hpp \
 src/point_2d.hpp \
 src/e_direction.hpp \
 src/game_context.hpp \
 src/i_damageable.hpp
entity_repair.o: src/GameObjects/entity_repair.hpp \
 src/entity_bonus.hpp src/entity.hpp \
 src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp
entity_speed.o: src/GameObjects/entity_speed.cpp \
 src/GameObjects/entity_speed.hpp src/entity_bonus.hpp \
 src/entity.hpp src/game_object.hpp \
 src/game_context.hpp src/i_physical.hpp \
 src/point_2d.hpp src/e_direction.hpp \
 src/texture_pack.hpp src/e_textures.hpp \
 src/world.hpp src/tile.hpp \
 src/GameObjects/tank.hpp \
 src/entity.hpp \
 src/i_directional.hpp \
 src/point_2d.hpp \
 src/e_direction.hpp \
 src/game_context.hpp \
 src/i_damageable.hpp
entity_speed.o: src/GameObjects/entity_speed.hpp \
 src/entity_bonus.hpp src/entity.hpp \
 src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp
explosion.o: src/GameObjects/explosion.cpp src/GameObjects/explosion.hpp \
 src/entity.hpp src/game_object.hpp \
 src/game_context.hpp src/i_physical.hpp \
 src/point_2d.hpp src/e_direction.hpp \
 src/texture_pack.hpp src/e_textures.hpp \
 src/i_damageable.hpp src/world.hpp \
 src/tile.hpp src/entity.hpp \
 src/GameObjects/tank.hpp \
 src/entity.hpp \
 src/i_directional.hpp \
 src/point_2d.hpp \
 src/e_direction.hpp \
 src/game_context.hpp \
 src/i_damageable.hpp
explosion.o: src/GameObjects/explosion.hpp src/entity.hpp \
 src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp
projectile.o: src/GameObjects/projectile.cpp \
 src/GameObjects/projectile.hpp src/entity.hpp \
 src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp src/i_directional.hpp \
 src/GameObjects/explosion.hpp src/tank_game.hpp \
 src/io_device.hpp src/world.hpp \
 src/tile.hpp src/entity.hpp \
 src/GameObjects/tank.hpp \
 src/entity.hpp \
 src/i_directional.hpp \
 src/i_damageable.hpp \
 src/game_context.hpp \
 src/game_context.hpp
projectile.o: src/GameObjects/projectile.hpp \
 src/entity.hpp src/game_object.hpp \
 src/game_context.hpp src/i_physical.hpp \
 src/point_2d.hpp src/e_direction.hpp \
 src/texture_pack.hpp src/e_textures.hpp \
 src/i_directional.hpp
tank.o: src/GameObjects/tank.cpp src/GameObjects/tank.hpp \
 src/entity.hpp src/game_object.hpp \
 src/game_context.hpp src/i_physical.hpp \
 src/point_2d.hpp src/e_direction.hpp \
 src/texture_pack.hpp src/e_textures.hpp \
 src/i_directional.hpp src/i_damageable.hpp \
 src/tank_game.hpp src/io_device.hpp \
 src/world.hpp src/tile.hpp \
 src/entity.hpp src/GameObjects/tank.hpp \
 src/world.hpp src/game_context.hpp \
 src/GameObjects/projectile.hpp src/GameObjects/explosion.hpp
tank.o: src/GameObjects/tank.hpp src/entity.hpp \
 src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp src/i_directional.hpp \
 src/i_damageable.hpp
tile_air.o: src/GameObjects/tile_air.cpp src/GameObjects/tile_air.hpp \
 src/tile.hpp src/game_object.hpp \
 src/game_context.hpp src/i_physical.hpp \
 src/point_2d.hpp src/e_direction.hpp \
 src/texture_pack.hpp src/e_textures.hpp
tile_air.o: src/GameObjects/tile_air.hpp src/tile.hpp \
 src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp
tile_bricks.o: src/GameObjects/tile_bricks.cpp \
 src/GameObjects/tile_bricks.hpp src/tile.hpp \
 src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp src/i_damageable.hpp \
 src/GameObjects/tile_air.hpp src/world.hpp \
 src/tile.hpp src/entity.hpp \
 src/GameObjects/tank.hpp \
 src/entity.hpp \
 src/i_directional.hpp \
 src/point_2d.hpp \
 src/e_direction.hpp \
 src/game_context.hpp \
 src/i_damageable.hpp
tile_bricks.o: src/GameObjects/tile_bricks.hpp \
 src/tile.hpp src/game_object.hpp \
 src/game_context.hpp src/i_physical.hpp \
 src/point_2d.hpp src/e_direction.hpp \
 src/texture_pack.hpp src/e_textures.hpp \
 src/i_damageable.hpp
tile_crate.o: src/GameObjects/tile_crate.cpp \
 src/GameObjects/tile_crate.hpp src/tile.hpp \
 src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp src/i_damageable.hpp \
 src/GameObjects/tile_air.hpp src/entity_bonus.hpp \
 src/entity.hpp src/world.hpp \
 src/tile.hpp src/GameObjects/tank.hpp \
 src/entity.hpp \
 src/i_directional.hpp \
 src/point_2d.hpp \
 src/e_direction.hpp \
 src/game_context.hpp \
 src/i_damageable.hpp
tile_crate.o: src/GameObjects/tile_crate.hpp src/tile.hpp \
 src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp src/i_damageable.hpp
tile_steel.o: src/GameObjects/tile_steel.cpp \
 src/GameObjects/tile_steel.hpp src/tile.hpp \
 src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp
tile_steel.o: src/GameObjects/tile_steel.hpp src/tile.hpp \
 src/game_object.hpp src/game_context.hpp \
 src/i_physical.hpp src/point_2d.hpp \
 src/e_direction.hpp src/texture_pack.hpp \
 src/e_textures.hpp
